---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mountpvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: crusoe-csi-driver-sc
  resources:
    requests:
      storage: 15Gi
  volumeMode: Filesystem
