{{ range $csiType, $csi := .Values.csi }}
{{ if $csi.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "crusoe-csi-driver.fullname" $ }}-{{ $csiType }}-node
spec:
  selector:
    matchLabels:
      app: {{ include "crusoe-csi-driver.fullname" $ }}-{{ $csiType }}
  template:
    metadata:
      labels:
        app: {{ include "crusoe-csi-driver.fullname" $ }}-{{ $csiType }}
    spec:
      hostPID: true
      serviceAccountName: {{ include "crusoe-csi-driver.fullname" $ }}-node
      {{- with $.Values.node.crusoeCsiDriver.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.node.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.node.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.node.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.node.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.node.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{ if eq $csiType "fs" }}
      initContainers:
        - name: install-nfs-prerequisites
          image: "{{ $.Values.node.installNfsPrerequisites.image.repository }}:{{ $.Values.node.installNfsPrerequisites.image.tag }}"
          command:
            - "/bin/sh"
          args:
            - "-c"
            - |
              cp /root/install.py /host/root/install.py
              nsenter -t 1 -m -u -i -n -p bash -ex -c "
              export DEBIAN_FRONTEND=noninteractive &&
              PACKAGES_TO_INSTALL=() &&
              command -v sudo >/dev/null 2>&1 || PACKAGES_TO_INSTALL+=(sudo) &&
              command -v curl >/dev/null 2>&1 || PACKAGES_TO_INSTALL+=(curl) &&
              command -v xz >/dev/null 2>&1 || PACKAGES_TO_INSTALL+=(xz-utils) &&
              if [ \${#PACKAGES_TO_INSTALL[@]} -gt 0 ]; then
                echo \"Installing missing utilities: \${PACKAGES_TO_INSTALL[*]}\" &&
                apt-get update -y &&
                apt-get install -y \${PACKAGES_TO_INSTALL[@]}
              else
                echo \"All utilities required for the installation process (sudo, curl, xz) are already installed\"
              fi &&
              mkdir -p /var/log/cmk &&
              echo 'Running install script...' &&
              /usr/bin/python3 -u /root/install.py -y | tee -a /var/log/cmk/install-nfs-prerequisites.log
              "
              exit $?
          volumeMounts:
            - name: install-script
              mountPath: "/root"
            - name: host-root
              mountPath: "/host"
          securityContext:
            privileged: true
          {{- with $.Values.node.installNfsPrerequisites.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      containers:
        - name: crusoe-csi-driver
          image: "{{ $.Values.node.crusoeCsiDriver.image.repository }}:{{ $.Values.node.crusoeCsiDriver.image.tag }}"
          imagePullPolicy: {{ $.Values.node.crusoeCsiDriver.image.imagePullPolicy }}
          command:
            - nsenter
          args:
            - "-t"
            - "1"
            - "-u"
            - "-i"
            - "-n"
            - "-p"
            - "/usr/local/go/bin/crusoe-csi-driver"
            - "--crusoe-csi-driver-type={{ $csiType }}"
            - "--services=node,identity"
            - "--socket-address=unix:/csi/{{ $csiType }}-node.sock"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- with $.Values.crusoe.nfs }}
            {{- with .remotePorts }}
            - name: NFS_REMOTE_PORTS
              value: {{ quote . }}
            {{- end }}
            {{- with .ip }}
            - name: NFS_IP
              value: {{ quote . }}
            {{- end }}
            {{- end }}
            {{- with $.Values.crusoe.api }}
            {{- with .endpoint }}
            - name: CRUSOE_API_ENDPOINT
              value: {{ quote . }}
            {{- else }}
            {{- if .fromSecret}}
            - name: CRUSOE_API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .fromSecret.name }}
                  key: {{ .fromSecret.endpointKeyPath }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- with $.Values.crusoe.projectID }}
            - name: CRUSOE_PROJECT_ID
              value: {{ . }}
            {{- end }}
            - name: CRUSOE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.crusoe.secrets.crusoeApiKeys.secretName }}
                  key: {{ $.Values.crusoe.secrets.crusoeApiKeys.accessKeyPath }}
            - name: CRUSOE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.crusoe.secrets.crusoeApiKeys.secretName }}
                  key: {{ $.Values.crusoe.secrets.crusoeApiKeys.secretKeyPath }}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
          securityContext:
            privileged: true
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 8084 # Using 8084 instead of 8082 to align with controller
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 2
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: 8084 # Using 8084 instead of 8082 to align with controller
            initialDelaySeconds: 0
            timeoutSeconds: 2
            periodSeconds: 2
          {{- with $.Values.node.crusoeCsiDriver.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: csi-driver-registrar
          image: "{{ $.Values.node.driverRegistrar.image.repository }}:{{ $.Values.node.driverRegistrar.image.tag }}"
          args:
            - "--v=5"
            - "--csi-address=/csi/{{ $csiType }}-node.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/{{ include "crusoe-csi-driver.fullname" $ }}/{{ $csiType }}-node.sock"
            - "--http-endpoint=0.0.0.0:8081"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 8084 # Use csi-liveness-probe endpoint to ensure csi-driver-registrar restarts when main crusoe-csi-driver restarts
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 2
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: 8084 # Use csi-liveness-probe endpoint to ensure csi-driver-registrar restarts when main crusoe-csi-driver restarts
            initialDelaySeconds: 0
            timeoutSeconds: 2
            periodSeconds: 2
        - name: csi-liveness-probe
          image: "{{ $.Values.node.livenessProbe.image.repository }}:{{ $.Values.controller.livenessProbe.image.tag }}"
          args:
            - "--v=5"
            - "--csi-address=/csi/{{ $csiType }}-node.sock"
            - "--http-endpoint=0.0.0.0:8084" # Using 8084 instead of 8082 to align with controller
            - "--metrics-path=/metrics"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        {{ if eq $csiType "fs" }}
        - name: install-script
          configMap:
            name: {{ include "crusoe-csi-driver.fullname" $ }}-{{ $csiType }}-install-nfs-prerequisites-script
            defaultMode: 0755
        - name: host-root
          hostPath:
            path: /
            type: Directory
        {{- end }}
        # This volume is where the socket for kubelet->driver communication is done
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/{{ include "crusoe-csi-driver.fullname" $ }}
            type: DirectoryOrCreate
          # This volume is where the driver mounts volumes
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
          # This volume is where the node-driver-registrar registers the plugin
          # with kubelet
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          # This volume is where devices are located on the underlying instance
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
      {{- with $.Values.node.customSpec }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{ end }}
{{ end }}