{{- range $index, $csi := .Values.csi }}
{{ if $csi.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "crusoe-csi-driver.fullname" $ }}-{{ $csi.csiType }}-node
spec:
  selector:
    matchLabels:
      app: {{ include "crusoe-csi-driver.fullname" $ }}-{{ $csi.csiType }}
  template:
    metadata:
      labels:
        app: {{ include "crusoe-csi-driver.fullname" $ }}-{{ $csi.csiType }}
    spec:
      serviceAccountName: {{ include "crusoe-csi-driver.fullname" $ }}-node
      {{- with $.Values.node.crusoeCsiDriver.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: crusoe-csi-driver
          image: "{{ $.Values.node.crusoeCsiDriver.image.repository }}:{{ $.Values.node.crusoeCsiDriver.image.tag }}"
          imagePullPolicy: {{ $.Values.node.crusoeCsiDriver.image.imagePullPolicy }}
          args:
            - "--crusoe-csi-driver-type={{ $csi.csiType }}"
            - "--services=node,identity"
            - "--socket-address=unix:/csi/{{ $csi.csiType }}-node.sock"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- with $.Values.crusoe.projectID }}
            - name: CRUSOE_PROJECT_ID
              value: {{ . }}
            {{- end }}
            - name: CRUSOE_CSI_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{$.Values.crusoe.secrets.crusoeApiKeys.secretName}}
                  key: {{$.Values.crusoe.secrets.crusoeApiKeys.accessKeyPath}}
            - name: CRUSOE_CSI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{$.Values.crusoe.secrets.crusoeApiKeys.secretName}}
                  key: {{$.Values.crusoe.secrets.crusoeApiKeys.secretKeyPath}}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: device-dir
              mountPath: /dev
          securityContext:
            privileged: true
          {{- with $.Values.node.crusoeCsiDriver.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: csi-driver-registrar
          image: "{{ $.Values.node.driverRegistrar.image.repository }}:{{ $.Values.node.driverRegistrar.image.tag }}"
          args:
            - "--v=5"
            - "--csi-address=/csi/{{ $csi.csiType }}-node.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/{{ include "crusoe-csi-driver.fullname" $ }}/{{ $csi.csiType }}-node.sock"
            - "--http-endpoint=0.0.0.0:8081"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
      volumes:
        # This volume is where the socket for kubelet->driver communication is done
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/{{ include "crusoe-csi-driver.fullname" $ }}
            type: DirectoryOrCreate
          # This volume is where the driver mounts volumes
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
          # This volume is where the node-driver-registrar registers the plugin
          # with kubelet
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          # This volume is where devices are located on the underlying instance
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
{{ end }}
{{ end }}