---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-mount
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: crusoe-csi-driver-ssd-sc
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
