---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockpvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: crusoe-csi-driver-sc
  resources:
    requests:
      storage: 10Gi
  volumeMode: Block
