apiVersion: v1
entries:
  crusoe-csi-driver:
  - apiVersion: v2
    appVersion: v0.1.5
    created: "2025-01-07T22:34:18.786235969Z"
    description: A Helm chart for the Crusoe Cloud CSI Driver
    digest: d18c7052c4f29f522d6e662ca3111df6c8b575d48b7c567ff181f4a538c49147
    home: https://github.com/crusoecloud/crusoe-csi-driver
    keywords:
    - crusoe
    - csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - name: Crusoe Cloud
      url: https://github.com/crusoecloud/crusoe-csi-driver/
    name: crusoe-csi-driver
    sources:
    - https://github.com/crusoecloud/crusoe-csi-driver
    type: application
    urls:
    - https://github.com/crusoecloud/crusoe-csi-driver-helm-charts/releases/download/crusoe-csi-driver-0.1.4/crusoe-csi-driver-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: v0.1.2
    created: "2024-11-25T20:36:14.053950932Z"
    description: A Helm chart for the Crusoe Cloud CSI Driver
    digest: 77609e5f7bec385fceee85f83b51e5b43610b10084503be4c9302dc6f8b6fb33
    home: https://github.com/crusoecloud/crusoe-csi-driver
    keywords:
    - crusoe
    - csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - name: Crusoe Cloud
      url: https://github.com/crusoecloud/crusoe-csi-driver/
    name: crusoe-csi-driver
    sources:
    - https://github.com/crusoecloud/crusoe-csi-driver
    type: application
    urls:
    - https://github.com/crusoecloud/crusoe-csi-driver-helm-charts/releases/download/crusoe-csi-driver-0.1.2/crusoe-csi-driver-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2024-11-23T03:41:09.875736609Z"
    description: A Helm chart for the Crusoe Cloud CSI Driver
    digest: 2975eea4578d3c88aa1c76b0a97cf5b36bc244dab2e5d1f82961e9ac32468a88
    home: https://github.com/crusoecloud/crusoe-csi-driver
    keywords:
    - crusoe
    - csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - name: Crusoe Cloud
      url: https://github.com/crusoecloud/crusoe-csi-driver/
    name: crusoe-csi-driver
    sources:
    - https://github.com/crusoecloud/crusoe-csi-driver
    type: application
    urls:
    - https://github.com/crusoecloud/crusoe-csi-driver-helm-charts/releases/download/crusoe-csi-driver-0.1.1/crusoe-csi-driver-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v0.0.14
    created: "2024-11-08T17:52:54.762843864Z"
    description: A Helm chart for the Crusoe Cloud CSI Driver
    digest: 04c1eb4c40fe6dd6abe993ec3d66be8a275ced45d15972936e714ce9eaf343cb
    home: https://github.com/crusoecloud/crusoe-csi-driver
    keywords:
    - crusoe
    - csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - name: Crusoe Cloud
      url: https://github.com/crusoecloud/crusoe-csi-driver/
    name: crusoe-csi-driver
    sources:
    - https://github.com/crusoecloud/crusoe-csi-driver
    type: application
    urls:
    - https://github.com/crusoecloud/crusoe-csi-driver-helm-charts/releases/download/crusoe-csi-driver-0.0.4/crusoe-csi-driver-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: v0.0.8
    created: "2024-10-10T03:20:59.731258333Z"
    description: A Helm chart for the Crusoe Cloud CSI Driver
    digest: 2f562dae069bde341e06991d4ef058148c5cbd0dac120b0d84510197757c84c1
    home: https://github.com/crusoecloud/crusoe-csi-driver
    keywords:
    - crusoe
    - csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - name: Crusoe Cloud
      url: https://github.com/crusoecloud/crusoe-csi-driver/
    name: crusoe-csi-driver
    sources:
    - https://github.com/crusoecloud/crusoe-csi-driver
    type: application
    urls:
    - https://github.com/crusoecloud/crusoe-csi-driver-helm-charts/releases/download/crusoe-csi-driver-0.0.2/crusoe-csi-driver-0.0.2.tgz
    version: 0.0.2
generated: "2025-01-07T22:34:18.786262278Z"
