---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharedfs-mount
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: crusoe-csi-driver-fs-sc
  resources:
    requests:
      storage: 15Ti
  volumeMode: Filesystem
