---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-block-ssd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-block-ssd
  template:
    metadata:
      labels:
        app: example-block-ssd
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: example-block-ssd
          image: ubuntu:24.04
          command: ["sleep", "infinity"]
          volumeDevices:
            - devicePath: "/dev/xvda"
              name: myblockdevice
      volumes:
        - name: myblockdevice
          persistentVolumeClaim:
            claimName: ssd-block
            readOnly: false
